## Numpy
- for working with arrays
- convention is to import numpy module as np

In [1]:
import numpy as np

## Indexing

- arrays go above and beyond what python built-in lists can do
- created by passing a list to the np.array function

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

- we can create multidimensional arrays

In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [5]:
a[0]

1

In [6]:
matrix[0]

array([1, 2, 3])

In [7]:
matrix[1]

array([4, 5, 6])

In [8]:
#to get the first two elements of the last two rows:
matrix[1:,:2] #[1: >> rows from index 1 onward, :2] elements of of rows 
# up to, not including index 2 (position 3)

array([[4, 5],
       [7, 8]])

In [9]:
a

array([1, 2, 3])

In [10]:
a[[True, False, True]]

array([1, 3])

## Boolean mask

In [11]:
should_include_elements_a = a[[True, False, True]]

In [12]:
should_include_elements_a

array([1, 3])

## Vectorized Operations
- add 1 to every element in a list
- easy to use
- easy to transform >> data into boolean values

In [13]:
numpy_array = np.array([1, 2, 3, 4, 5])
numpy_array + 1

array([2, 3, 4, 5, 6])

In [14]:
print(numpy_array + 2)

[3 4 5 6 7]


In [15]:
my_array = np.array([-3, 0, 3, 16])

In [16]:
print(f'my_array - 5 == {my_array - 5}')

my_array - 5 == [-8 -5 -2 11]


In [32]:
print(f'my_array >= 0 == {my_array >= 0}') ##Boolean mask against comp ops

my_array >= 0 == [False  True  True  True]


In [18]:
my_array[my_array > 0] ##conditionals >> show me which data is greater 
                        #than 0

array([ 3, 16])

## In Depth Example
- obtain all even numbers
- syntax notes: and = "&", or = "|"

In [19]:
my_array[my_array % 2 == 0]

array([ 0, 16])

In [20]:
my_array % 2

array([1, 0, 1, 0])

## Array Creation
- standard normal distribution

In [21]:
## create random number arrays
np.random.randn(10)
## standard normal distribution from 1 to inf, with mean 0, std dev 1

array([-0.48944777, -0.31240031,  0.00473631,  1.31026146,  0.81286971,
        0.56861889, -0.28286513,  0.41354217,  1.16759673, -2.50365341])

In [22]:
## create random number arrays, in two dimensions
np.random.randn(3, 4) # 4 things in a line, 3 times

array([[ 0.72267987,  0.29172271,  1.68151642,  0.63353565],
       [-0.36485316, -0.67620416,  0.1194366 ,  0.72088096],
       [ 2.14955287,  0.80811057,  0.81146385, -0.59218958]])

## np.zeroes, np.ones, np.full

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
np.full((3,4), 'ASAP')

array([['ASAP', 'ASAP', 'ASAP', 'ASAP'],
       ['ASAP', 'ASAP', 'ASAP', 'ASAP'],
       ['ASAP', 'ASAP', 'ASAP', 'ASAP']], dtype='<U4')

## np.arange

In [28]:
# can take a single argument and generate a range zero to passed num
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1, 10, 3.5)

array([1. , 4.5, 8. ])

## np.linspace

In [31]:
#create a range of numbers between a min and a max, with a set 
#number of elements
np.linspace(1, 10, 7)

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

## Array methods

np.min()
np.max()
np.sum()
np.std()