## Control Structures

In [1]:
## IF

it_is_raining = False
if it_is_raining:
    print("Bring an umbrella")
else:
    print("Have a nice day")

Have a nice day


In [2]:
##ELIF checks multiple conditions

coffee_preference = 'medium'

if coffee_preference == 'dark':
    print("I love dark")
elif coffee_preference == 'medium':
    print("I love medium")
elif coffee_preference == 'light':
    print('Light roast is best')
else:
    print("Tea?")

I love medium


In [6]:
## For Loops
for number in range(1, 4):
    print(number)
    
for letter in 'abcde':
    print(letter)
    
languages = ['bash', 'python', 'clojure', 'R']
for programming_language in languages:
    print(f'{programming_language} is a nice language')
    

1
2
3
a
b
c
d
e
bash is a nice language
python is a nice language
clojure is a nice language
R is a nice language


In [8]:
## While loops

i = 5
while i <= 10:
    print(i)
    i += 1

5
6
7
8
9
10


In [9]:
## Break stops executing a loop when a condition is met
for n in range(100000):
    print(n)
    if n > 10:
        break

0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
## Continue will skip to the next iteration of a loop
for n in range(10):
    if n % 2 == 0:
        continue
    print(f'here is an odd number: {n}')

here is an odd number: 1
here is an odd number: 3
here is an odd number: 5
here is an odd number: 7
here is an odd number: 9


## FUNCTIONS

In [13]:
## built in functions

print(max([4, 3, 2, 1]))

print(min([4, 3, 2, 1]))

4
1


In [14]:
## Variable assignment:
max_number = max([4, 3, 2, 1])
print(max_number)

4


In [15]:
##Defining fucntions:
def increment(n):
    return n + 1

increment(3)

4

In [17]:
##Nesting
increment(increment(increment(3)))

6

## IMPORTS

In [19]:
## package install in terminal

#conda install (package)

#pip install (package)

import math

import pandas as pf

import numpy as np

## DS LIBRARIES

### MATPLOTLIB

In [20]:
import matplotlib.pyplot as plt

In [22]:
%matplotlib inline 
##print in Jupyter w/o show command

In [23]:
##scatter plots
# plt.scatter(x, y)

### NUMPY

In [24]:
import numpy as np

- arrays

In [26]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
matrix[0]

array([1, 2, 3])

In [28]:
matrix[1,1]

5

In [29]:
matrix[0, 0]

1

In [32]:
should_include_elements = [True, False, True]
matrix[should_include_elements]
##removes second index

array([[1, 2, 3],
       [7, 8, 9]])

## VECTORIZED OPERATIONS

In [33]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matrix + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [35]:
matrix[matrix > 5]

array([6, 7, 8, 9])

In [36]:
matrix[matrix < 8]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
matrix % 2

array([[1, 0, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [39]:
result = matrix % 2
result == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

### methods

.min()/.max()/.sum()/.mean()/.std()

## PANDAS

### Series

In [40]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt


- creation: numbers_series = pd.Series( [ ] )

- labeled series: labeled_series = pd.Series({'a':0, 'b':1})

### Vectorized operations

In [41]:
numbers_series = pd.Series([100, 43, 26, 17, 17])
type(numbers_series)

pandas.core.series.Series

In [42]:
numbers_series + 4

0    104
1     47
2     30
3     21
4     21
dtype: int64

In [43]:
numbers_series == 21

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [44]:
numbers_series > 50

0     True
1    False
2    False
3    False
4    False
dtype: bool

### Attributes

.index/.values/.dtype/.name/.size/.shape

### Methods

.head/.tail/.sample

transform the type with: .astype() >> float, int, str

summarize info with: .value_counts()

.describe()

.count()/.sum()/.median()/.mean()/.mode()/.abs()/.std()/.quantile()

.nlargest(n=5, keep='first') #5 largest values, keeps only 1 duplicate

### DATAFRAMES

creation: df = pd.DataFrame

df.info()/.describe()/.dtypes/.shape/.columns/.index

- accessing multiple columns: df[['name', 'math']]

- single column: df.math , df['math']

Accessing subsets:

    - .head()/.tail()/.sample()
    
    - df.column </>/= results in a boolean
    
    - df[df.math < 100] will yield df rows where condition is True

DROP and RENAME:
    
    -df.drop(columns=['1':'2'])
    
    -df.rename(columns={'a','b'})

## NOTES AFTER ASSESSMENT

pain points: 

    - variable names
    
    - quick use of & |
    
    - variable setting: df =
    
takeaways

    - slow it down
    
    df.value_counts() shows column names and values, so we can correctly reference variables. Use this to double check
    
    - use mulitple cells to break down operations into chunks